MACHINE = "raspberrypi0-2w-64"
CMDLINE:append = " cma=128M"
TMPDIR .= "-${BB_CURRENT_MC}"

RPI_EXTRA_CONFIG += 'dtoverlay=arducam-pivariety \n'

KERNEL_DEVICETREE:append = " overlays/arducam-pivariety.dtbo"

OVERRIDES:append = ":air"

IMAGE_INSTALL:append = " openhd rtl88x2bu linux-firmware libcamera kernel-modules libcamera-apps raspi-gpio iw networkmanager"
IMAGE_BASENAME = "air-rpi0-image"
hostname:pn-base-files = "air-rpi0-image"
