MACHINE = "raspberrypi4-64"
TMPDIR .= "-${BB_CURRENT_MC}"

IMAGE_INSTALL:append = " openhd qopenhd rtl88x2bu linux-firmware kernel-modules raspi-gpio iw networkmanager"

DISTRO_FEATURES:append = " opengl egl drm"
OVERRIDES:append = ":ground"

# Enable the hardware acceleration and DRM glue
PACKAGECONFIG:append:pn-qtbase = " gles2 eglfs kms"

# Enable the GStreamer/Qt bridge
PACKAGECONFIG:append:pn-gst-plugins-good = " qt5"

IMAGE_BASENAME = "ground-rpi4-image"
hostname:pn-base-files = "ground-rpi4-image"
