MACHINE = "raspberrypi4-64"
TMPDIR .= "-${BB_CURRENT_MC}"

IMAGE_INSTALL:append = " openhd qopenhd rtl88x2bu linux-firmware kernel-modules raspi-gpio iw networkmanager"

DISTRO_FEATURES:append = " opengl egl drm"
PREFERRED_PROVIDER_virtual/libgles2 = "mesa"
PREFERRED_PROVIDER_virtual/egl = "mesa"

OVERRIDES:append = ":ground"

PACKAGECONFIG:append:pn-qtbase = " gles2 eglfs kms"

PACKAGECONFIG:append:pn-gst-plugins-good = " qt5"

PREFERRED_PROVIDER_ffmpeg = "ffmpeg"
PREFERRED_PROVIDER_libav = "ffmpeg"

IMAGE_BASENAME = "ground-rpi4-image"
hostname:pn-base-files = "ground-rpi4-image"
